In [47]:
from __future__ import print_function
import keras
from os import listdir
from os.path import isfile, join
import os
from keras.datasets import mnist
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from sklearn.model_selection import train_test_split
from keras import backend as K
import numpy as np

batch_size = 100
num_classes = 10
epochs = 120

# input image dimensions
img_rows, img_cols = 64, 64

# the data, split between train and test sets
# (x_train, y_train), (x_test, y_test) = mnist.load_data()

In [20]:
dir_path = "/home/jon/Documents/workspace/free-spoken-digit-dataset/spectrograms_all/"
file_names = [f for f in listdir(dir_path) if isfile(join(dir_path, f)) and '.png' in f]
lst = []
y = []
for f in file_names:
    temp = plt.imread(dir_path+f, )
    y.append(int(f[0]))
    lst.append(temp)
X = np.asarray(lst)
Y = np.asarray(y)

In [21]:
# lsttmp = []
# for i in Y :
#     tmp = []
#     for numbers in range(10) :
#         if numbers == i :
#             num = 1
#         else :
#             num = 0
#         tmp.append(num)
#     lsttmp.append(tmp)
# Y = np.asarray(lsttmp)
# Y

In [57]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [58]:
y_train

array([1, 3, 5, ..., 5, 9, 2])

In [59]:
if K.image_data_format() == 'channels_first':
    x_train = x_train.reshape(x_train.shape[0], 4, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 4, img_rows, img_cols)
    input_shape = (4, img_rows, img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 4)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 4)
    input_shape = (img_rows, img_cols, 4)



In [60]:

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print(x_train.shape)
print(y_train.shape)

(1340, 64, 64, 4)
(1340, 10)


In [62]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# 
model = Sequential()
# model.add(Conv2D(6, kernel_size=(3, 3),
#                  activation='relu',
#                  input_shape=input_shape))
# model.add(Conv2D(12, (3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Dropout(0.25))
# model.add(Flatten())
model.add(Flatten())
model.add(Dense(512, activation='relu', input_shape=input_shape))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.001, momentum=0.9),
              metrics=['accuracy'])

model.fit(x_train, y_train,
#           batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_split=0.1)
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

x_train shape: (1340, 64, 64, 4)
1340 train samples
660 test samples
Train on 1206 samples, validate on 134 samples
Epoch 1/120
1206/1206 [==============================] - 2s 1ms/step - loss: 2.3027 - acc: 0.0920 - val_loss: 2.3025 - val_acc: 0.0970
Epoch 2/120
1206/1206 [==============================] - 0s 248us/step - loss: 2.3027 - acc: 0.0879 - val_loss: 2.3027 - val_acc: 0.0672
Epoch 3/120
1206/1206 [==============================] - 0s 246us/step - loss: 2.3024 - acc: 0.1103 - val_loss: 2.3027 - val_acc: 0.0672
Epoch 4/120
1206/1206 [==============================] - 0s 244us/step - loss: 2.3024 - acc: 0.0962 - val_loss: 2.3026 - val_acc: 0.0672
Epoch 5/120
1206/1206 [==============================] - 0s 246us/step - loss: 2.3023 - acc: 0.1061 - val_loss: 2.3027 - val_acc: 0.0970
Epoch 6/120
1206/1206 [==============================] - 0s 244us/step - loss: 2.3022 - acc: 0.0954 - val_loss: 2.3027 - val_acc: 0.0672
Epoch 7/120
1206/1206 [==============================] - 0s 246u

1206/1206 [==============================] - 0s 236us/step - loss: 2.3013 - acc: 0.1078 - val_loss: 2.3051 - val_acc: 0.0672
Epoch 60/120
1206/1206 [==============================] - 0s 238us/step - loss: 2.3014 - acc: 0.1078 - val_loss: 2.3052 - val_acc: 0.0672
Epoch 61/120
1206/1206 [==============================] - 0s 255us/step - loss: 2.3014 - acc: 0.1078 - val_loss: 2.3053 - val_acc: 0.0672
Epoch 62/120
1206/1206 [==============================] - 0s 241us/step - loss: 2.3014 - acc: 0.1078 - val_loss: 2.3051 - val_acc: 0.0672
Epoch 63/120
1206/1206 [==============================] - 0s 244us/step - loss: 2.3012 - acc: 0.1078 - val_loss: 2.3053 - val_acc: 0.0672
Epoch 64/120
1206/1206 [==============================] - 0s 233us/step - loss: 2.3010 - acc: 0.1078 - val_loss: 2.3053 - val_acc: 0.0672
Epoch 65/120
1206/1206 [==============================] - 0s 237us/step - loss: 2.3014 - acc: 0.1078 - val_loss: 2.3052 - val_acc: 0.0672
Epoch 66/120
1206/1206 [=======================

1206/1206 [==============================] - 0s 253us/step - loss: 2.3015 - acc: 0.1078 - val_loss: 2.3055 - val_acc: 0.0672
Epoch 119/120
1206/1206 [==============================] - 0s 237us/step - loss: 2.3015 - acc: 0.1078 - val_loss: 2.3056 - val_acc: 0.0672
Epoch 120/120
1206/1206 [==============================] - 0s 245us/step - loss: 2.3014 - acc: 0.1078 - val_loss: 2.3057 - val_acc: 0.0672
Test loss: 2.308111806349321
Test accuracy: 0.09242424244681995


In [63]:
y_pred = model.predict(x_test)

In [64]:
y_pred.argmax(axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [43]:
y_pred[0]

array([0.0985565 , 0.10572608, 0.09942745, 0.097695  , 0.10432712,
       0.10236169, 0.09227589, 0.10220782, 0.1024944 , 0.09492807],
      dtype=float32)

In [36]:
temp = [1==i for i in Y]
Y[temp].size

200

In [37]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_14 (Conv2D)           (None, 62, 62, 6)         222       
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 60, 60, 12)        660       
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 30, 30, 12)        0         
_________________________________________________________________
dropout_13 (Dropout)         (None, 30, 30, 12)        0         
_________________________________________________________________
flatten_7 (Flatten)          (None, 10800)             0         
_________________________________________________________________
dense_15 (Dense)             (None, 128)               1382528   
_________________________________________________________________
dense_16 (Dense)             (None, 64)                8256      
__________

In [44]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.]], dtype=float32)

In [45]:
y_pred

array([[0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807],
       [0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807],
       [0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807],
       ...,
       [0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807],
       [0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807],
       [0.0985565 , 0.10572608, 0.09942745, ..., 0.10220782, 0.1024944 ,
        0.09492807]], dtype=float32)