In [87]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
from os import listdir
from os.path import isfile, join
import os
from matplotlib.image import imread
import matplotlib.pyplot as plt
import scipy.io.wavfile as wav

In [88]:
dir_path = '/home/jon/Documents/workspace/free-spoken-digit-dataset/recordings/'
file_names = [f for f in listdir(dir_path) if isfile(join(dir_path, f)) and '.wav' in f]

In [89]:
lst = []
for file_name in file_names :
#     print(file_name)
    sample_rate, sample = wav.read(dir_path+file_name)
    lst.append([sample, file_name])

In [90]:
lst

[[array([ 9, 10,  9, ...,  7, -1,  3], dtype=int16), '9_yweweler_14.wav'],
 [array([-316, -336, -342, ..., -442, -424, -310], dtype=int16),
  '0_jackson_18.wav'],
 [array([-256, -512, -256, ..., -256,    0,    0], dtype=int16),
  '0_nicolas_28.wav'],
 [array([ 10,   1,  13, ...,  -9, -13, -13], dtype=int16), '0_yweweler_0.wav'],
 [array([-6,  7,  8, ..., 26, 28,  0], dtype=int16), '8_theo_27.wav'],
 [array([   0, -256,  512, ...,    0,    0,    0], dtype=int16),
  '5_nicolas_35.wav'],
 [array([-984,   27,  189, ...,  401,  373,  367], dtype=int16),
  '3_jackson_21.wav'],
 [array([-567,   59, -255, ..., -261, -268, -302], dtype=int16),
  '2_jackson_17.wav'],
 [array([-256,    0, -256, ...,    0, -256,    0], dtype=int16),
  '4_nicolas_26.wav'],
 [array([ 3,  6, -2, ..., 13,  6,  6], dtype=int16), '1_yweweler_26.wav'],
 [array([-2, 10, -1, ...,  1,  6,  2], dtype=int16), '7_theo_12.wav'],
 [array([-42, -36, -30, ..., -42,  -8,   3], dtype=int16), '0_theo_38.wav'],
 [array([-152, -149, -1

In [116]:
def len_of_wav(e) :
    """
    :e    : nparray, the array of that wav
    :rtype: lenth of e
    """
    return len(e[0])

def purify(inwave, maxlength) :
    """
    :inwave : nparray original wave and file name
    :rtype: nparray purified wave, cut prefix 0 and suffix 0
    """
    wave = inwave[0]
    print(wave)
    tmp = np.zeros(maxlength)
#     print(wave)
    if wave[0] == 0 :
        prefix_zero = True
    else :
        prefix_zero = False
    cnt = 0
    for i in range(len(wave)) :
        if prefix_zero and wave[i] == 0 :
            continue
        else :
            prefix_zero = False
            tmp[cnt] = wave[i]
            cnt += 1
    return [tmp, inwave[1]]

In [117]:
lst.sort(key=len_of_wav)

In [118]:
res = []
for i in lst :
#     print(i)
    res.append(purify(i, 8000))
    

[-2 -7 -7 ...  3 -1  0]
[-1024  -256   768 ... -7168 -4864 -7936]
[ -8  -9  -8 ...  -5 -12  -6]
[-256 -256 -512 ... -256 -512 -256]
[  4   4  -4 ...  -4 -16  -4]
[-5 -3  0 ...  1 13 11]
[ 256  256  256 ... -512 -256 -512]
[ 512 1024 1024 ... -256 -256 -512]
[-3  0 -4 ...  2 -2 -2]
[-256    0 -256 ... -256 -512    0]
[ 3  3  3 ... 64 72 72]
[ 1  8  1 ... -8  1  4]
[ 512  256  256 ... -512 -256 -256]
[11  4 -5 ... -3  6  5]
[   0 -256 -256 ...    0    0 -256]
[   0    0  256 ... -256    0 -256]
[-256 -256    0 ... -256 -256    0]
[  1 -10  -6 ... -14 -22  -4]
[ -8  -7   0 ... -18 -22 -20]
[-7 -5 -5 ...  0  6  9]
[ 0  7  2 ... 13 18 -4]
[-512 -256 -512 ...    0 -256    0]
[ 256  256  256 ... -256 -512 -256]
[   0 -256 -256 ... -256 -256 -256]
[-1  2 -3 ...  8  1 -7]
[  0   0   0 ... 256   0 256]
[   0    0 -256 ... -512 -256 -512]
[-6  8  3 ... -4 -1 -5]
[ -7 -11 -11 ...   5  -2  -7]
[ 512  256 -256 ...    0 -512    0]
[ 10  10   3 ... -33 -34 -29]
[-142  -88  -66 ...  106  108   74]
[-29

[-16  15  19 ...  34  41  52]
[ 4 -5 -7 ... -3  0  0]
[   0    0    0 ...    0 -256    0]
[-768  256 -512 ... -256    0    0]
[-768    0 -256 ... -256 -512    0]
[   0 -256 -256 ... -256 -512 -256]
[-256 -256 -256 ... -768 -512 -512]
[-256 -256    0 ...    0    0 -256]
[-6 -3 -7 ... -5  4 -6]
[   0 -512    0 ...  256  256  256]
[-256    0    0 ... -256 -512 -256]
[   0 -256 -256 ... -256    0 -256]
[ -5 -10  -9 ...  -1  -6  -4]
[ 2  0 -1 ...  6 -3 -7]
[-2  0 -2 ... -1  3 18]
[-256    0 -512 ...    0 -256    0]
[ 2  6  5 ... -3  3  4]
[-11  -4  -9 ...  -5  -9  -9]
[-2  3 -1 ... -1  2 -4]
[-4  4 -5 ... -1  9 -3]
[   0    0 -256 ... -512 -512 -768]
[-9  5  5 ... 14 12 15]
[-19 -12  -5 ...  -9 -27  -7]
[   0 -512 -256 ... -256 -256 -512]
[-256 -256    0 ... -512 -256 -256]
[ -1  -1   1 ...  16 -13  -3]
[   0 -256 -256 ... -256 -256    0]
[ 48 -37  36 ... -21 -33 -62]
[  4  -3   8 ...   4   9 -50]
[-2  0 -1 ... 10 14 13]
[-2 -3  5 ...  1 20 28]
[1024  768 1024 ... -256 -512    0]
[0 0 0 ...

[   0    0 -256 ...    0 -256    0]
[   0 -512    0 ... -768 -512 -768]
[-256 -512 -256 ... -256    0    0]
[-39 -41 -40 ... -34 -52 -52]
[-256 -256    0 ... -256 -256 -512]
[  7   7   9 ... -14   2 -13]
[-1693  -432 -1706 ...    90   -59  -403]
[-12 -12 -13 ...  -5 -11   0]
[ -7  10  11 ...  -1  -2 -11]
[-768 -768 -512 ... -256 -512 -256]
[ 9  9 -7 ...  1 -7 19]
[  4   3   2 ... -11 -11 -19]
[ 256 -256    0 ... -256 -256    0]
[   0    0    0 ...    0 -256    0]
[  0 -12  -8 ...  15   0   1]
[ 27 -13  54 ... -23   9  -7]
[ -4 -18 -14 ...   3  -2   7]
[   0  256    0 ...  256 -256    0]
[ 0 -1 -1 ... -3 -5 -1]
[-6  1  4 ... 53 35 22]
[-20   7 -24 ...  12   1  -5]
[-743 -212 -159 ... -382 -303 -352]
[ 13  -9   1 ... -13  -3   1]
[-256 -256 -512 ... -256    0    0]
[-256 -256    0 ...    0 -256    0]
[-256 -256 -256 ... -256 -256 -256]
[ 2 -3  2 ...  1 11 13]
[ 0  1 -1 ... 13 11 10]
[  1   1   1 ...  -4  -1 -10]
[-10  -7   0 ...  -4   8  19]
[ 13   5   9 ...  -7 -14 -12]
[-49  25 -27 ...

[18 -5  9 ... 23  5 36]
[ -3  20  -3 ... -21  53   0]
[-256    0    0 ...    0 -256 -256]
[14 -7 18 ...  4  9 -2]
[   0 -256    0 ... -256 -512 -256]
[-8 12 13 ... 20 14  3]
[ -2   1  -4 ...   1   5 -12]
[  8  20  74 ... -45  40  -2]
[-10  -5  16 ...  14   8   4]
[ 331  372  402 ...  -53 -148 -315]
[-256    0 -256 ... -256 -256 -256]
[-11  -8  -5 ...  -6  -6 -10]
[-256 -512 -256 ... -256 -256 -256]
[ -3 -17  -1 ...  -4   2   8]
[-19 -19 -21 ...   9   8  10]
[   0    0    0 ... -256 -512 -256]
[ -6 -23 -37 ... -40 -25 -11]
[ -8   2   1 ... -32   4 -23]
[ 26 -25 -45 ...  12  43  16]
[-256    0 -256 ... -256    0 -256]
[-256    0 -256 ... -256    0 -256]
[-12  -4  -3 ...   2   9   8]
[ 8 17 14 ...  4  4  8]
[-353  -54   24 ...  188  240  364]
[-1013  -479  -150 ...  -287  -343  -336]
[ 27  26  20 ... -38 -25 -35]
[  2  -6   1 ... -20 -21 -17]
[-58  48  52 ...  12  41  28]
[   0    0    0 ... -256 -256 -256]
[ 66  13  26 ... -24  63 -35]
[  0   0  -2 ... -12  -5  -5]
[ 446  126  -31 ... -3

[-256 -256 -256 ...    0 -256    0]
[-913   69 -225 ... -283 -320 -303]
[302 324 393 ... 305 300 309]
[-414 -572 -505 ...  236  283  307]
[-37  35 -44 ... -15 -36   9]
[ -6  -2  -5 ... -23 -12 -11]
[   0  256    0 ... -256    0 -256]
[-645 -613 -346 ...  429  408  366]
[-256    0 -256 ... -256 -512 -256]
[59 61 54 ... 37 29 31]
[-5  9  3 ... 26 16 21]
[ 303  309  278 ... -213  -39  413]
[  7  11  12 ... -19 -15 -15]
[  6   2   6 ... -12  -9  -5]
[   0    0 -256 ...    0 -256    0]
[16  3 -8 ... 10 10  2]
[-16   1  -2 ... -22 -30  -3]
[-256 -256 -256 ...    0    0    0]
[-256 -256 -256 ... -512 -256 -512]
[  7  -7   0 ... -17  -8 -19]
[-2 -4 -2 ... -2  2 -3]
[-387  -13  -20 ...   95  202  325]
[-256    0    0 ... -256    0 -256]
[ 11   0   6 ... -32  12   0]
[-318   77   12 ... -279 -300 -324]
[ 383  520  541 ... -142 -210 -302]
[-519 -299   27 ...   53  285  321]
[   0  256    0 ... -512 -256 -512]
[-378  -80  102 ...  327  346  328]
[  2 -21  -7 ...   1  34  16]
[ 4  5 -1 ... -9  4  8

[ 307 -238  265 ... -414 -330 -358]
[-349  337 -207 ... -389 -383 -322]
[-301 -301 -302 ... -387 -347 -305]
[-1227   119  -366 ...  -319  -323  -306]
[-3 -6  0 ... -2 -2 -6]
[-302 -263 -245 ...  350  379  305]
[-42 -36 -30 ... -42  -8   3]
[-165 -209 -249 ...  161  178  155]
[-302 -312 -103 ... -338 -333 -348]
[-186   93  -38 ...   20  -40  168]
[ 318  357  373 ... -360 -324 -305]
[  1   1 -11 ...  18 -14 -36]
[-329 -327 -369 ... -465 -412 -354]
[ -8  12  -3 ... -19 -17  19]
[  373 -1558   778 ...   301   328   312]
[-512 -256 -512 ... -512 -256 -256]
[334 358 385 ... 122 152 311]
[   0    0    0 ... -256 -512 -256]
[  570  -949 -1277 ...  -282  -310  -323]
[-393   54  -71 ...  319  340  313]
[-499  347 -547 ... -262 -270 -304]
[  2   1   0 ... -15 -14 -16]
[ 342 -250  248 ...  310  352  346]
[-1238   625   416 ...  -307  -314  -309]
[-256    0 -256 ... -512 -256 -512]
[-417  152  168 ...  312  316  309]
[-360   49 -225 ... -219 -247 -315]
[ -7  -1  21 ... -38  20  -9]
[ -2  -1   0 ...

IndexError: index 8000 is out of bounds for axis 0 with size 8000

In [119]:
res

[[array([-2., -7., -7., ...,  0.,  0.,  0.]), '6_yweweler_3.wav'],
 [array([-1024.,  -256.,   768., ...,     0.,     0.,     0.]),
  '6_nicolas_7.wav'],
 [array([-8., -9., -8., ...,  0.,  0.,  0.]), '6_yweweler_1.wav'],
 [array([-256., -256., -512., ...,    0.,    0.,    0.]), '6_nicolas_9.wav'],
 [array([ 4.,  4., -4., ...,  0.,  0.,  0.]), '2_theo_34.wav'],
 [array([-5., -3.,  0., ...,  0.,  0.,  0.]), '6_yweweler_17.wav'],
 [array([256., 256., 256., ...,   0.,   0.,   0.]), '6_nicolas_35.wav'],
 [array([ 512., 1024., 1024., ...,    0.,    0.,    0.]), '6_nicolas_23.wav'],
 [array([-3.,  0., -4., ...,  0.,  0.,  0.]), '6_yweweler_10.wav'],
 [array([-256.,    0., -256., ...,    0.,    0.,    0.]), '6_nicolas_38.wav'],
 [array([3., 3., 3., ..., 0., 0., 0.]), '4_yweweler_8.wav'],
 [array([1., 8., 1., ..., 0., 0., 0.]), '6_yweweler_23.wav'],
 [array([512., 256., 256., ...,   0.,   0.,   0.]), '6_nicolas_36.wav'],
 [array([11.,  4., -5., ...,  0.,  0.,  0.]), '6_yweweler_25.wav'],
 [array

8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
8000
